<?php
// Include the database connection file (conn.php)
require_once('conn.php');

// Check if the database connection was successful
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}

// Function to fetch products sorted by brand and then by stock
function getProductsSortedByBrandAndStock($conn) {
    $sql = "SELECT * FROM products ORDER BY type ASC, stock ASC"; // 'type' is assumed to be the brand
    $result = mysqli_query($conn, $sql);

    if (mysqli_num_rows($result) > 0) {
        $products = array();
        while ($row = mysqli_fetch_assoc($result)) {
            $products[] = $row;
        }
        return $products;
    } else {
        return array(); // Return an empty array if no products are found
    }
}

// Fetch the products, sorted by brand and stock
$products = getProductsSortedByBrandAndStock($conn);

// --- PDF Generation using TCPDF ---
// Include the TCPDF library (you'll need to download and install it)
// IMPORTANT: Use the full path to tcpdf.php, and ensure it's correct.
require_once('../vendor/autoload.php');

// Create a new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Jepsoft'); // Created by Jepsoft
$pdf->SetAuthor('Hyper Selo'); // Generated by Hyper Selo
$pdf->SetTitle('Stock Report');
$pdf->SetSubject('Products Stock Report (By Brand and Stock)');
$pdf->SetKeywords('stock, report, products, low stock, high stock, brand');

// Set default header data (optional - customize as needed)
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Stock Report', 'Products Sorted by Brand and Stock', array(0, 64, 255), array(0, 64, 128));
$pdf->setFooterData(array(0, 64, 0), array(0, 64, 128));

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
    require_once(dirname(__FILE__) . '/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// Set default font
$pdf->SetFont('dejavusans', '', 8); // Use a Unicode font like dejavusans

// Add a page
$pdf->AddPage();

// --- Generate the HTML table for the PDF ---
$html = '
    <!DOCTYPE html>
    <html>
    <head>
    <title>Stock Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 8pt;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 4px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }
        .center {
            text-align: center;
        }
        .bold {
            padding: 5px;
        }
        .boldn {
            padding: 5px;
            font-weight: bold;
        }
    </style>
    </head>
    <body>
        <h1>Stock Report (By Brand)</h1>
        <p>Generated by: <strong>Hyper Selo</strong></p> 
        <p>Created by: <strong>Jepsoft</strong></p>
        <table class="bold">
            <thead>
                <tr>
                    <th class="boldn">Product Name</th>
                    <th class="boldn">Brand</th>
                    <th class="boldn">AH</th>
                    <th class="boldn">Stock</th>
                    <th class="boldn">Warranty</th>
                    <th class="boldn">Price</th>
                    <th class="boldn">Created At</th>
                </tr>
            </thead>
            <tbody>';

if (empty($products)) {
    $html .= '<tr><td colspan="13" class="center">No products found.</td></tr>';
} else {
    $currentBrand = null; // Keep track of the current brand
    foreach ($products as $product) {
        // If the brand changes, add a heading row
        if ($product['type'] != $currentBrand) { // 'type' is assumed to be the brand
            if ($currentBrand !== null) {
                $html .= '<tr><td colspan="7" style="border-top: 2px solid #000;"></td></tr>'; // Add a line before the new brand
            }
            $html .= '<tr><td colspan="7" style="font-size: 12pt; font-weight: bold; background-color: #f8f8f8;">Brand: ' . $product['type'] . '</td></tr>';
            $currentBrand = $product['type'];
        }
        $html .= '
                    <tr>
                        <td>' . $product['title'] . '</td>
                        <td>' . $product['type'] . '</td>
                        <td>' . (isset($product['ah']) ? $product['ah'] : '-') . '</td>
                        <td>' . $product['stock'] . '</td>
                        <td>' . $product['warranty'] . '</td>
                        <td>' . $product['price'] . '</td>
                        <td>' . $product['created_at'] . '</td>
                    </tr>';
    }
}
$html .= '
            </tbody>
        </table>
    </body>
    </html>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// --- Output the PDF ---
$pdf->Output('stock_report.pdf', 'D'); // 'D' forces a download

// Close the database connection
mysqli_close($conn);
?>
